name: Register and Issue using cert-manager
on:
  #push:
  schedule:
    - cron: "50 6 * * *"

jobs:
  cert-manager-register-and-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install things
      - uses: azure/setup-helm@v3
      - uses: actions/setup-python@v4
      - uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: ct.yaml

      - uses: helm/kind-action@v1.7.0

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: ct.yaml

